name: Auto Retrain

on:
  push:
    paths:
      - 'data/*.pdf'

jobs:
  train:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev git
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt


    - name: Train model
      run: python train.py

    - name: Commit model
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add trained_model/
        git commit -m "Update model"
        git push
