name: Automatic Retraining Pipeline

on:
  push:
    paths:
      - 'data/**'  # Triggers only when PDFs in data/ folder change

jobs:
  retrain-model:
    runs-on: ubuntu-latest
    timeout-minutes: 120  # Increase if training takes longer
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        sudo apt-get install -y python3-dev python3-pdfminer

    - name: Run training pipeline
      run: python train.py

    - name: Commit updated model
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add trained_model/
        git commit -m "[Bot] Auto-commit updated model" || echo "No changes to commit"
        git push
